CREATE TABLE [dbo].[Jobs] (
	[Id]		    NVARCHAR (100) PRIMARY KEY NOT NULL,
    [JobName]       NVARCHAR (100) NULL,
    [CompanyName]   NVARCHAR (255) NULL,
    [Salary]        NVARCHAR (100) NULL,
    [JobLocation]   NVARCHAR (100) NULL,
    [Experience]    NVARCHAR (MAX) NULL,
    [Description]   NVARCHAR (MAX) NULL,
    [Require]       NVARCHAR (MAX) NULL,
    [Benefit]       NVARCHAR (MAX) NULL,
    [WorkTime]      NVARCHAR (MAX) NULL,
);
INSERT INTO Jobs (Id, JobName, CompanyName, Salary, JobLocation, Experience, Description, Require, Benefit, WorkTime)
VALUES
('1', 'Kỹ sư phần mềm', 'Tập đoàn công nghệ', 'Mức lương cạnh tranh (Thỏa thuận)', 'Thành phố Hồ Chí Minh, Việt Nam (Linh hoạt/Có thể từ xa)', 'Hơn 2 năm kinh nghiệm trong phát triển phần mềm (Java, Ưu tiên Python, C++)', 'Phát triển, duy trì và triển khai các giải pháp phần mềm phức tạp sử dụng các phương pháp Agile. Cộng tác làm việc với nhóm kỹ sư để thiết kế và cung cấp các sản phẩm phần mềm chất lượng cao.', 'Kỹ năng lập trình vững vàng, khả năng giải quyết vấn đề, và kinh nghiệm lập trình hướng đối tượng. Kỹ năng giao tiếp và làm việc nhóm tốt. Đam mê đổi mới và học hỏi không ngừng.', 'Mức lương và phúc lợi cạnh tranh, bảo hiểm y tế, cơ hội phát triển nghề nghiệp, môi trường làm việc năng động.', 'Toàn thời gian (Linh hoạt). số giờ có thể)'), 
('2', 'Nhà phân tích dữ liệu', 'Financial Inc.', 'Mức lương + thưởng hấp dẫn', 'Hà Nội, Việt Nam', '3+ năm kinh nghiệm trong phân tích dữ liệu (ưu tiên Excel, SQL ), Lập mô hình tài chính', 'Thực hiện phân tích dữ liệu tài chính chuyên sâu để xác định xu hướng và tạo ra những hiểu biết có giá trị về kinh doanh. Đề xuất các chiến lược đầu tư và hỗ trợ việc ra quyết định tài chính.', 'Kỹ năng phân tích mạnh mẽ, thành thạo các công cụ phân tích dữ liệu (Excel, SQL) và kỹ thuật lập mô hình tài chính. Khả năng giao tiếp và kĩ năng thuyết trình tuyệt vời. Khả năng làm việc độc lập và theo nhóm.', 'Gói lương và phúc lợi cạnh tranh, bảo hiểm y tế, cơ hội thưởng, chương trình phát triển nghề nghiệp.', 'Toàn thời gian (40 giờ mỗi tuần)'), 

('3', 'Giám đốc tiếp thị', 'Doanh nghiệp toàn cầu', 'Mức lương cạnh tranh + Tiền thưởng hiệu suất', ' Singapore', 'Hơn 5 năm kinh nghiệm tiếp thị với thành tích thành công đã được chứng minh. Kinh nghiệm trong tiếp thị kỹ thuật số và thương mại điện tử chiến lược là một điểm cộng.', 'Dẫn dắt và quản lý nhóm tiếp thị hiệu suất cao để phát triển và thực hiện các chiến dịch tiếp thị thành công và đạt được mức tăng trưởng lợi nhuận cho công ty.', 'Kỹ năng lãnh đạo mạnh mẽ, kinh nghiệm phát triển và thực hiện các chiến lược tiếp thị, kỹ năng giao tiếp và giao tiếp cá nhân xuất sắc. Kiến thức chuyên sâu về các kênh tiếp thị kỹ thuật số và xu hướng thương mại điện tử.', 'Gói phúc lợi và mức lương cạnh tranh, bảo hiểm y tế, cơ hội thưởng, hỗ trợ di chuyển (nếu có).', 'Toàn thời gian (40). giờ mỗi tuần)'),
('4', 'Nhà phát triển ứng dụng di động', 'Phòng thí nghiệm sáng tạo', 'Mức lương cạnh tranh + Tùy chọn cổ phiếu', 'Đà Nẵng, Việt Nam (Có thể từ xa)', 'Hơn 2 năm kinh nghiệm phát triển ứng dụng di động (React Native, Flutter được ưu tiên)', 'Phát triển và duy trì các ứng dụng di động sáng tạo cho nhiều nền tảng khác nhau. Đóng góp vào môi trường làm việc có nhịp độ nhanh và hợp tác.', 'Kỹ năng lập trình vững chắc trong các khung phát triển ứng dụng di động (React Native, Flutter). một điểm cộng. Kỹ năng giao tiếp và làm việc nhóm xuất sắc.', 'Gói lương và phúc lợi cạnh tranh, bảo hiểm y tế, lựa chọn cổ phiếu, sắp xếp công việc linh hoạt (có thể từ xa).', 'Toàn thời gian (có thể có giờ linh hoạt)'),
('5' , 'Nhà thiết kế đồ họa', 'Đại lý AdMax', 'Mức lương cạnh tranh + Phúc lợi', 'Cần Thơ, Việt Nam', '3 năm kinh nghiệm trở lên trong thiết kế đồ họa (ưu tiên Adobe Photoshop, Illustrator)', 'Phát triển đồ họa sáng tạo và hấp dẫn về mặt hình ảnh tài liệu thiết kế cho các chiến dịch tiếp thị và sáng kiến ​​xây dựng thương hiệu.', 'Thành thạo phần mềm thiết kế đồ họa (Adobe Photoshop, Illustrator). Có kinh nghiệm về các nguyên tắc tiếp thị và xây dựng thương hiệu là một lợi thế. Kỹ năng giao tiếp và hợp tác xuất sắc.', 'Mức lương và phúc lợi cạnh tranh, bảo hiểm y tế, cơ hội phát triển nghề nghiệp, môi trường làm việc sáng tạo.', 'Toàn thời gian (40 giờ mỗi tuần)');
