CREATE TABLE [dbo].[Jobs] (
	[Id]		    NVARCHAR (100) PRIMARY KEY NOT NULL,
    [JobName]       NVARCHAR (100) NULL,
    [CompanyName]   NVARCHAR (255) NULL,
    [Salary]        NVARCHAR (100) NULL,
    [JobLocation]   NVARCHAR (100) NULL,
    [Experience]    NVARCHAR (MAX) NULL,
    [Description]   NVARCHAR (MAX) NULL,
    [Require]       NVARCHAR (MAX) NULL,
    [Benefit]       NVARCHAR (MAX) NULL,
    [WorkTime]      NVARCHAR (MAX) NULL,
);
INSERT INTO Jobs (Id, JobName, CompanyName, Salary, JobLocation, Experience, Description, Require, Benefit, WorkTime)
VALUES
('1', N'Kỹ sư phần mềm', N'FPT SoftWare', N'Mức lương cạnh tranh (Thỏa thuận)', N'Thành phố Hồ Chí Minh, Việt Nam (Linh hoạt/Có thể từ xa)', N'Hơn 2 năm kinh nghiệm trong phát triển phần mềm (Java, Ưu tiên Python, C++)', N'Phát triển, duy trì và triển khai các giải pháp phần mềm phức tạp sử dụng các phương pháp Agile. Cộng tác làm việc với nhóm kỹ sư để thiết kế và cung cấp các sản phẩm phần mềm chất lượng cao.', N'Kỹ năng lập trình vững vàng, khả năng giải quyết vấn đề, và kinh nghiệm lập trình hướng đối tượng. Kỹ năng giao tiếp và làm việc nhóm tốt. Đam mê đổi mới và học hỏi không ngừng.', N'Mức lương và phúc lợi cạnh tranh, bảo hiểm y tế, cơ hội phát triển nghề nghiệp, môi trường làm việc năng động.', N'Toàn thời gian (Linh hoạt). số giờ có thể)'), 
('2', N'Nhà phân tích dữ liệu', N'Financial Inc.', N'Mức lương + thưởng hấp dẫn', N'Hà Nội, Việt Nam', N'3+ năm kinh nghiệm trong phân tích dữ liệu (ưu tiên Excel, SQL ), Lập mô hình tài chính', N'Thực hiện phân tích dữ liệu tài chính chuyên sâu để xác định xu hướng và tạo ra những hiểu biết có giá trị về kinh doanh. Đề xuất các chiến lược đầu tư và hỗ trợ việc ra quyết định tài chính.', N'Kỹ năng phân tích mạnh mẽ, thành thạo các công cụ phân tích dữ liệu (Excel, SQL) và kỹ thuật lập mô hình tài chính. Khả năng giao tiếp và kĩ năng thuyết trình tuyệt vời. Khả năng làm việc độc lập và theo nhóm.', N'Gói lương và phúc lợi cạnh tranh, bảo hiểm y tế, cơ hội thưởng, chương trình phát triển nghề nghiệp.', N'Toàn thời gian (40 giờ mỗi tuần)'), 
('3', N'Giám đốc tiếp thị', N'Doanh nghiệp toàn cầu', N'Mức lương cạnh tranh + Tiền thưởng hiệu suất', N'Nước ngoài', N'Hơn 5 năm kinh nghiệm tiếp thị với thành tích thành công đã được chứng minh. Kinh nghiệm trong tiếp thị kỹ thuật số và thương mại điện tử chiến lược là một điểm cộng.', N'Dẫn dắt và quản lý nhóm tiếp thị hiệu suất cao để phát triển và thực hiện các chiến dịch tiếp thị thành công và đạt được mức tăng trưởng lợi nhuận cho công ty.', N'Kỹ năng lãnh đạo mạnh mẽ, kinh nghiệm phát triển và thực hiện các chiến lược tiếp thị, kỹ năng giao tiếp và giao tiếp cá nhân xuất sắc. Kiến thức chuyên sâu về các kênh tiếp thị kỹ thuật số và xu hướng thương mại điện tử.', N'Gói phúc lợi và mức lương cạnh tranh, bảo hiểm y tế, cơ hội thưởng, hỗ trợ di chuyển (nếu có).', N'Toàn thời gian (40). giờ mỗi tuần)'),
('4', N'Nhà phát triển ứng dụng di động', N'Phòng thí nghiệm sáng tạo', N'Mức lương cạnh tranh + Tùy chọn cổ phiếu', N'Đà Nẵng, Việt Nam (Có thể từ xa)', N'Hơn 2 năm kinh nghiệm phát triển ứng dụng di động (React Native, Flutter được ưu tiên)', N'Phát triển và duy trì các ứng dụng di động sáng tạo cho nhiều nền tảng khác nhau. Đóng góp vào môi trường làm việc có nhịp độ nhanh và hợp tác.', N'Kỹ năng lập trình vững chắc trong các khung phát triển ứng dụng di động (React Native, Flutter). một điểm cộng. Kỹ năng giao tiếp và làm việc nhóm xuất sắc.', N'Gói lương và phúc lợi cạnh tranh, bảo hiểm y tế, lựa chọn cổ phiếu, sắp xếp công việc linh hoạt (có thể từ xa).', N'Toàn thời gian (có thể có giờ linh hoạt)'),
('5' , N'Nhà thiết kế đồ họa', N'Đại lý AdMax', N'Mức lương cạnh tranh + Phúc lợi', N'Cần Thơ, Việt Nam', N'3 năm kinh nghiệm trở lên trong thiết kế đồ họa (ưu tiên Adobe Photoshop, Illustrator)', N'Phát triển đồ họa sáng tạo và hấp dẫn về mặt hình ảnh tài liệu thiết kế cho các chiến dịch tiếp thị và sáng kiến ​​xây dựng thương hiệu.', N'Thành thạo phần mềm thiết kế đồ họa (Adobe Photoshop, Illustrator). Có kinh nghiệm về các nguyên tắc tiếp thị và xây dựng thương hiệu là một lợi thế. Kỹ năng giao tiếp và hợp tác xuất sắc.', N'Mức lương và phúc lợi cạnh tranh, bảo hiểm y tế, cơ hội phát triển nghề nghiệp, môi trường làm việc sáng tạo.', N'Toàn thời gian (40 giờ mỗi tuần)'),
('6', N'Chuyên viên thiết kế đồ họa', N'Đại lý AdMax', N'Thỏa thuận', N'Cần Thơ, Việt Nam', N'', N'Thực hiện các chiến dịch quảng cáo sáng tạo, thiết kế đồ họa cho các sản phẩm và dịch vụ.', N'Kỹ năng thiết kế đồ họa, kiến thức về marketing.', N'Cơ hội phát triển nghề nghiệp.', N'Toàn thời gian'),
('7', N'Nhân viên phát triển ứng dụng di động', N'Creative Labs', N'Thỏa thuận', N'Đà Nẵng, Việt Nam', N'', N'Phát triển và duy trì các ứng dụng di động trên nền tảng Android và iOS.', N'Kỹ năng lập trình ứng dụng di động, đam mê công nghệ.', N'Cơ hội phát triển nghề nghiệp.', N'Toàn thời gian'),
('8', N'Chuyên viên phân tích tài chính', N'Financial Inc.', N'Thỏa thuận', N'Hà Nội, Việt Nam', N'', N'Phân tích dữ liệu tài chính, đưa ra các khuyến nghị về đầu tư và quản lý tài sản.', N'Kiến thức về tài chính, kỹ năng phân tích dữ liệu.', N'Các phúc lợi cạnh tranh.', N'Toàn thời gian'),
('9', N'Kỹ sư phần mềm Java', N'FPT SoftWare', N'Thỏa thuận', N'Thành phố Hồ Chí Minh, Việt Nam', N'Từ 3 năm kinh nghiệm trong phát triển phần mềm Java', N'Phát triển và triển khai các ứng dụng doanh nghiệp sử dụng Java.', N'Kỹ năng lập trình Java, kiến thức về phát triển phần mềm.', N'Mức lương và phúc lợi cạnh tranh.', N'Toàn thời gian'),
('10', N'Chuyên viên phân tích dữ liệu', N'FPT SoftWare', N'Thỏa thuận', N'Thành phố Hồ Chí Minh, Việt Nam', N'', N'Phân tích dữ liệu và đưa ra các giải pháp cải thiện hiệu suất kinh doanh.', N'Kiến thức về phân tích dữ liệu, kỹ năng sử dụng các công cụ phân tích.', N'Mức lương và phúc lợi cạnh tranh.', N'Toàn thời gian'),
('11', N'Chuyên viên hỗ trợ khách hàng', N'Financial Inc.', N'Thỏa thuận', N'Hà Nội, Việt Nam', N'', N'Hỗ trợ khách hàng giải quyết các vấn đề liên quan đến tài chính và dịch vụ.', N'Kỹ năng giao tiếp, kiến thức về tài chính.', N'Các phúc lợi cạnh tranh.', N'Toàn thời gian'),
('12', N'Nhân viên quản lý dự án', N'Doanh nghiệp toàn cầu', N'Thỏa thuận', N'Singapore', N'', N'Quản lý và triển khai các dự án thương mại điện tử và tiếp thị.', N'Kỹ năng quản lý dự án, kiến thức về thương mại điện tử.', N'Theo quy định.', N'Toàn thời gian');





